/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package harapan;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author JORDAN ISTIQLAL
 */
public class TransaksiT extends javax.swing.JFrame {
            String kira ="D:\\MATA KULIAH\\Data Pembeli\\Pembeli.txt";
    /**
     * Creates new form TransaksiT
     */
    public TransaksiT() {
        initComponents();
    }
    void Data(){
        Data.setText("");
        
        String bang = "";
        
        try {
            Scanner file = new Scanner(new File(kira));
            while(file.hasNext()){
                bang += file.nextLine();
//                System.out.println(bang);
//                Data.setText(bang);
            }
            String bro[] = bang.split("+");
            
            for(int i =0 ;i < bro.length;i++){
                Data.append(bro[i] + " \n ");
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        daerah = new javax.swing.JTextField();
        kerja1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        H1 = new javax.swing.JTextField();
        combo1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        H2 = new javax.swing.JTextField();
        P1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        L1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tambah = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Data = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Kirane", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Daerah");

        jLabel3.setText("Pekerjaan");

        jLabel4.setText("Alamat");

        daerah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daerahActionPerformed(evt);
            }
        });

        kerja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerja1ActionPerformed(evt);
            }
        });

        alamat1.setColumns(20);
        alamat1.setRows(5);
        jScrollPane2.setViewportView(alamat1);

        jLabel5.setText("OPSI TANAH");

        jLabel6.setText("Jenis Tanah");

        jButton4.setText(">");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Harga /Meter");

        H1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        H1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H1ActionPerformed(evt);
            }
        });

        combo1.setBackground(new java.awt.Color(204, 204, 204));
        combo1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Pilih---", "Sawah", "Pegunungan ", "Perkotaan", "Ladang", "Pantai" }));
        combo1.setToolTipText("");
        combo1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        combo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Panjang ");

        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        H2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        H2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                H2ActionPerformed(evt);
            }
        });

        P1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        P1.setText("0");
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });

        jButton2.setText(">");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Meter");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Lebar");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Meter");

        jButton3.setText("<");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        L1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        L1.setText("0");
        L1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                L1ActionPerformed(evt);
            }
        });

        jLabel12.setText("Rp");

        jLabel13.setText("Rp");

        tambah.setBackground(new java.awt.Color(153, 153, 255));
        tambah.setText("Buka Data");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        simpan.setBackground(new java.awt.Color(51, 255, 0));
        simpan.setText("Ulang");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(255, 0, 51));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(255, 153, 0));
        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        jButton6.setText("Total");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("No");

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setText("Tambah");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(L1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(P1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(H1)
                                    .addComponent(H2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama)
                            .addComponent(jScrollPane2)
                            .addComponent(daerah)
                            .addComponent(kerja1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(47, 47, 47)
                                .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 90, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(daerah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kerja1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(combo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(P1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton4)
                                .addComponent(jLabel11)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(H1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(H2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jButton6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambah)
                    .addComponent(simpan)
                    .addComponent(reset)
                    .addComponent(edit)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Data.setColumns(20);
        Data.setRows(5);
        jScrollPane1.setViewportView(Data);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String a1 = L1.getText();

        int an1 = Integer.parseInt(a1);

        an1 +=10;

        String a2 = Integer.toString(an1);

        L1.setText(a2);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void H1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H1ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        String harga = null;

        if (combo1.getSelectedItem()=="---pilih---"){
            H1.setText("");
            H2.setText("");
            H1.setEnabled(false);
            H2.setEnabled(false);
            combo1.requestFocus();
        }else {
            if(combo1.getSelectedItem()=="Sawah"){
                harga = "125000";

            }else if (combo1.getSelectedItem()=="Pegununggan"){
                harga = "1200000";
            }else if (combo1.getSelectedItem()=="Perkotaan"){
                harga = "1500000";
            }else if (combo1.getSelectedItem()=="Ladang"){
                harga = "500000";
            }else {
                harga = "3000000";
            }
            H1.setText(harga);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a1 = P1.getText();

        int an1 = Integer.parseInt(a1);

        an1 -=10;

        String a2 = Integer.toString(an1);

        P1.setText(a2);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_P1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a1 = P1.getText();

        int an1 = Integer.parseInt(a1);

        an1 +=10;

        String a2 = Integer.toString(an1);

        P1.setText(a2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String a1 = L1.getText();

        int an1 = Integer.parseInt(a1);

        an1 -=10;

        String a2 = Integer.toString(an1);

        L1.setText(a2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void L1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_L1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_L1ActionPerformed

    private void H2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_H2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_H2ActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
    no.setText("");
    nama.setText("");
    daerah.setText("");
    kerja1.setText("");
    alamat1.setText(""); 
    combo1.setSelectedIndex(0);
    P1.setText("0");
    L1.setText("0");
    H1.setText("");
    H2.setText("");

            String N    =(no.getText());
            String Name=(nama.getText());
            String Daerah=(daerah.getText());
            String Pekerjaan=(kerja1.getText());
            String Alamat=(alamat1.getText());
            String harga1 =(H1.getText());
            String harga2 =(H2.getText());
       String pembeli =no.getText()+" || "+ nama.getText()+" || "+daerah.getText()+" || "+kerja1.getText()+" || "+alamat1.getText()+" || "+H1.getText()+" || "+H2.getText();

        File ae1 = new File ("D:\\MATA KULIAH\\Data Pembeli");
        String sementara = "";
        try{
            Scanner file =new Scanner(new File(kira));
            while(file.hasNext()){
                sementara += file.next();}
            
            PrintWriter kr=new PrintWriter("D:\\MATA KULIAH\\Data Pembeli\\Pembeli.txt");
            kr.println(pembeli);
//            kr.println(N);
//            kr.println(Name);
//            kr.println(Daerah);
//            kr.println(Pekerjaan);
//            kr.println(Alamat);
//            kr.println(harga1);
//            kr.println(harga2);
                kr.close();
        }catch (Exception x){
            System.out.println(x); 
            }        
        if(ae1.exists()){
            
        }else {
            ae1.mkdir();
        }
        
        JOptionPane.showMessageDialog(null,"TERIMA KASIH,DATA ANDA AKAN KAMI PROSES");// TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        String sae ="";
        String tanah ="";
        if(combo1.getSelectedItem()=="---Pilih---"){
            H1.setText("");
            H2.setText("");
            H1.setEnabled(false);
            H2.setEnabled(false);
            combo1.requestFocus();
        }else{
            if(combo1.getSelectedItem()=="Sawah"){
                tanah = "125000";
            }else if (combo1.getSelectedItem()=="Pegununggan"){
                tanah = "1200000"; 
        }else if (combo1.getSelectedItem()=="Perkotaan"){
                tanah = "1500000";
            }else if (combo1.getSelectedItem()=="Ladang"){
                tanah = "500000";
            }else {
                tanah = "3000000";
            }
            H1.setText(tanah);
            
        try {
            Scanner file = new Scanner(new File(kira));
            while (file.hasNext()){
                sae += file.nextLine();
            }
        } catch (Exception e) {
            System.out.println(e);
        }  
        }
        String bro[] = sae.split(" + ");
        for (int i = 0;i<bro.length;i++){
            
            String kang[] = bro[i].split(" + ");
            if(kang[0].equals(no.getText())){
                bro[i] =no.getText()+" || "+ nama.getText()+" || "+daerah.getText()+" || "+kerja1.getText()+" || "+alamat1.getText()+" || "+H1.getText()+" || "+H2.getText();
            }
        }
        String kumpul ="";
        try {
            PrintWriter kr = new PrintWriter(kira);
            for(int i = 0;i<bro.length;i++){
                kumpul += bro[i]+" \n ";
            }
            Data();
            kr.print(kumpul);
            kr.close();
            JOptionPane.showMessageDialog(null,"Terima Kasih..");
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_editActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        simpan.setEnabled(false);
        tambah.setEnabled(false);
        edit.setEnabled(false);
        reset.setEnabled(false);

        String A1 = P1.getText();
        String A2 = L1.getText();
        String A3 = H1.getText();

        int a1  = Integer.parseInt(A1);
        int a2  = Integer.parseInt(A2);
        int a3  = Integer.parseInt(A3);
        int a4;
        int a5;

        try{
            a4=a1*a2;
            a5 =a4*a3;
         
            String b1 = Integer.toString(a5);
            H2.setText(b1);
            
        }catch(Exception x){
            System.out.println(x);
                    
        }
        H1.setEnabled(false);
        H2.setEnabled(false);
        simpan.setEnabled(true);
        tambah.setEnabled(true);
        edit.setEnabled(true);
        reset.setEnabled(true);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
     String sementara = "";
        try {
            Scanner file = new Scanner(new File(kira));
            while (file.hasNext()) {
                sementara += file.nextLine();
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        String pisah[] = sementara.split(" + ");
        
        for (int i = 0; i < pisah.length; i++) {
            
            String kolom[] = pisah[i].split(" || ");
            if (kolom[0].equals(no.getText())) {
                for (int n = i ; n < pisah.length-1; n++) {
                     pisah[n] = pisah[n + 1];
                }
              JOptionPane.showMessageDialog(null, "Data Berhasil diHapus");  
            }  
        }
        String kumpul = "";
        try {
            PrintWriter kr = new PrintWriter(kira);
            for(int i = 0 ; i< pisah.length-1;i++){
                kumpul += pisah[i]+" \n ";
            }
            kr.print(kumpul);
            kr.close();
            
            Data();
        } catch (Exception e) {
            System.out.println(e);
        }

    
// TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
    String kata = "" ;
    
        try{
            Scanner baca = new Scanner(new File (kira));
            while(baca.hasNext()){
                kata += baca.nextLine();
//                System.out.println(kata);
//                Data.setText(kata);
            }
            //Biar turun
            String turun [] = kata.split(" + ");
            
            for(int i = 0;i <turun.length;i++){
                Data.append(turun[i] + " \n ");
//                Data();
            }
            
            
        }catch(Exception v){
            System.out.println(v);
        }
            // TODO add your handling code here:
    }//GEN-LAST:event_tambahActionPerformed

    private void daerahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daerahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_daerahActionPerformed

    private void kerja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kerja1ActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
           String bang ="";
           try {
            Scanner file = new Scanner(new File(kira));
            while (file.hasNext()){
                bang += file.nextLine();
            }
            String bro[] = bang.split(" + ");
            for(int i = 0; i < bro.length ;i++){
                String kang[] = bro[i].split(" || ");
                if(kang[0].equals(no.getText())){
                no.setText(kang[0]);
                nama.setText(kang[1]);
                daerah.setText(kang[2]);
                kerja1.setText(kang[3]);
                alamat1.setText(kang[4]);
                
//                if(kang[6].equals("Sawah")){
//                    combo1.setSelectedItem(true);
//                }else if(kang[6].equals("Pegungguan")){
//                    combo1.setSelectedItem(true);
//                }else if(kang[6].equals("Perkotaan")){
//                    combo1.setSelectedItem(true);
//                }else if(kang[6].equals("Ladang")){
//                    combo1.setSelectedItem(true);
//                }else {
//                    combo1.setSelectedItem(true);
//                }
                
                combo1.setSelectedItem(kang[5]);
                P1.setText(kang[6]);
                L1.setText(kang[7]);
                H1.setText(kang[8]);
                H2.setText(kang[9]);
            }}
        } catch (Exception e) {
               System.out.println(e);
        }
        }
{
               
          
// TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String sae ="";
        try {
            Scanner file = new Scanner(new File(kira));
            while (file.hasNext()){
                sae += file.nextLine();
//                System.out.println(sae);
//                Data.setText(sae);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
       
       
        
        String aa []  = sae.split(" + ");
        
         
        
        String tanah = "";
        if(combo1.getSelectedItem()=="Sawah"){
            tanah = "125000";
        }else if(combo1.getSelectedItem()=="Pegunggan"){
            tanah = "1200000";
        }else if (combo1.getSelectedItem()=="Perkotaan"){
            tanah = "1500000";
        }else if (combo1.getSelectedItem()=="Ladang"){
            tanah = "500000";
        }else {
            tanah = "3000000";
        }
        String pembeli1 =no.getText()+" || "+ nama.getText()+" || "+daerah.getText()+" || "+kerja1.getText()+" || "+alamat1.getText()+" || "+H1.getText()+" || "+H2.getText();
        try {
            PrintWriter kn =new PrintWriter(kira);
            for(int i = 0; i < aa.length;i++){
                kn.print(aa[i] + " \n ");
            }
            kn.print(pembeli1 + " \n ");
            kn.close();
            
//            Data();
        } catch (Exception e) {
            System.out.println(e);
        } 
        
        JOptionPane.showMessageDialog(null,"Terima Kasih Data Anda sedang kami proses");// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Data;
    private javax.swing.JTextField H1;
    private javax.swing.JTextField H2;
    private javax.swing.JTextField L1;
    private javax.swing.JTextField P1;
    private javax.swing.JTextArea alamat1;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JTextField daerah;
    private javax.swing.JButton edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kerja1;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
